spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5435/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true # Mostra o Sql No terminal
    hibernate:
      ddl-auto: none # Atualiza/Cria o banco automaticamente baseado no código
#      ddl-auto: update
    properties:
      hibernate.format_sql: true