spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: sisi
  jpa:
    database-plataform: org.hibernate.dialect.H2dialect
  h2:
    console:
      enabled: true
    path: /h2-console